apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
components:
    - ../../../../components/project-admin-rolebindings/varangian
    - ../../../../components/limitranges/default
    - ../../../../components/resourcequotas/small
namespace: varangian-test
