apiVersion: kustomize.config.k8s.io/v1beta1
components:
- ../../../../components/project-admin-rolebindings/thoth-devops
- ../../../../components/project-admin-rolebindings/operate-first
- ../../../../components/project-admin-rolebindings/octo-training-model
- ../../../../components/monitoring-rbac
- ../../../../components/limitranges/default
kind: Kustomization
namespace: opf-ci-pipelines
resources:
- namespace.yaml
- resourcequota.yaml
