---
apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
spec:
  storage:
    $patch: replace
    managementState: Unmanaged
    s3:
      bucket: "openshift-image-registry-760235ec-9dc0-46a8-88e1-1f8e96908c63"
      regionEndpoint: "https://s3-openshift-storage.apps.smaug.na.operate-first.cloud"
      region: "-"
