---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../../../components/project-admin-rolebindings/boatroackers
- ../../../../components/resourcequotas/large
- ../../../../components/limitranges/default

namespace: boatrockers

resources:
- namespace.yaml
