---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cosigned-webhook
  labels:
    helm.sh/chart: cosigned-v0.1.9
    app.kubernetes.io/name: cosigned
    app.kubernetes.io/instance: cosigned
    app.kubernetes.io/version: "v1.4.1"
    app.kubernetes.io/managed-by: Helm
    control-plane: cosigned-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cosigned-webhook
subjects:
- kind: ServiceAccount
  name: cosigned-webhook
  namespace: cosign-system
