kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: chrisproject
resources:
    - namespace.yaml
components:
    - ../../../../components/limitranges/default
    - ../../../../components/project-admin-rolebindings/redhat-impact
    - ../../../../components/resourcequotas/large
