apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
components:
    - ../../../../components/project-admin-rolebindings/fybrik
    - ../../../../components/limitranges/default
    - ../../../../components/resourcequotas/large
namespace: fybrik-applications
