apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
components:
    - ../../../../components/project-admin-rolebindings/prometheus-anomaly-detector
    - ../../../../components/resourcequotas/large
    - ../../../../components/limitranges/default
namespace: prometheus-anomaly-detector
